### ISSUE TITLE
Data Download!!!

### ISSUE THREAD

**Issue by jishnujayakumar** [rllab-snu/TopologicalSemanticGraphMemory#7]
Hi @bareblackfoot, 

Great work. I am trying to download [data](https://mysnu-my.sharepoint.com/:f:/g/personal/blackfoot_seoul_ac_kr/EoYVFXO2_3lNhho_7LdmAU4B9A669tgjNbSd0ukc_AKXtQ?e=eRheUZ) as mentioned [here](https://github.com/rllab-snu/TopologicalSemanticGraphMemory#download-data). Since the size of the data was too large, it often happened that after downloading 30-40% of the data, the download stops due to some reason. This behavior stands when using browser download. Is there a way to get using scripts so that the chances of download stoppage somehow get low? 

**PS: Having a shareable link might help for the `graph/train` and `graph_il_data` directories as they have the largest file size.**

**Comment by bareblackfoot** [comment]
Hi, jishnujayakumar.
Thanks for your interest in TSGM!

Unfortunately, the OneDrive for Business provided by SNU does not offer a sharable link, which makes downloading from the command line impossible. I will move the files to my Google Drive and generate a shareable link (this weekend).

However, I recommend that you run the code to create the data since the training data is too large to share directly. You can generate similar data using the provided code.

**Comment by jishnujayakumar** [comment]
Thank you @bareblackfoot for the response. I will check it. Also, the ImgEncoder.pth.tar link is invalid. I am not able to run build_tgsm.ipynb due to that.

**Comment by bareblackfoot** [comment]
I updated link now :)
I will check that the imgEncoder.pth.tar in build_tsgm.ipynb.
I close this issue for now since it was about the data download!
